spring:
    application:
      name: gateway-service

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMiliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  ribbon:
    eager-load: 
      enabled: true
  routes:
    users: 
      path: /user-service/**
      url: http://localhost:8090/
    expenses: 
      path: /expense-service/**
      url: http://localhost:8091/
    budgets: 
      path: /budget-service/**
      url: http://localhost:8092/
    incomes: 
      path: /income-service/**
      url: http://localhost:8093/
  sensitive-headers:
    ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  
server:
  port: 8765